import Head from 'next/head'
import styles from '../styles/Home.module.css'
import TasksProgress from '../componets/tasksProgress'
import TaskItem from '../componets/taskItem'
import { useState, useEffect, useContext } from 'react'


export default function Home() {

  const [tasks, setTasks] = useState([])


    const [taskTitle, setTaskTitle] = useState("")
    const [taskTime, setTaskTime] = useState("")
    const [taskColor, setTaskColor] = useState("pink")
    const [taskStatus, setTaskStatus] = useState(false)
    
    useEffect(() => {
    const res = localStorage.getItem("todos")
    res != null? setTasks(JSON.parse(res)) : setTasks([])
    }, [])

 
    
  

  return (
    <div className={styles.container}>
      <Head>
        <title>Million Dollar Todo App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icon.png" />
      </Head>

    <main>
        <h1 className={styles.title}>Home</h1>
      <header className={styles.greeting_container}>
        <div >
          <p className={styles.greeting}>Hello</p>
          <p className={styles.greeting}>Munyaradzi</p>
        </div>
      </header>
      <section>
        <TasksProgress total={tasks.length} done={1} progress={1 / tasks.length * 100 + "%"}/>  
      </section>
      <section>
        {/* <input type="text" onChange={(e) => setTaskTitle(e.target.value)}/>
        <button onClick={() => setTasks(tasks.concat(
          {title: taskTitle, time: "9:00 AM", color: "#afe5c1", status: true}
  ))}>Add task</button> */}
          <span>Todays Tasks</span>
          {tasks && tasks.map(x => 
          <TaskItem key={x.title} color={x.color} title={x.title} time={x.time}/>
          )}
      </section>
    </main>
    </div>
  )
}
